version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-nest
    environment:
      MYSQL_ROOT_PASSWORD: daraja
      MYSQL_DATABASE: e-learningdb
      MYSQL_USER: dar
      MYSQL_PASSWORD: daraja
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
